parameters:
  brand_directory: '%kernel.project_dir%/public/uploads/brands'
  perfume_directory: '%kernel.project_dir%/public/uploads/perfumes'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\:
    resource: '../src/*'
    exclude: '../src/{DependencyInjection,Entity,Tests}'