parameters:
    brand_directory: '%kernel.project_dir%/public/uploads/brands'
services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests}'
    
